.TH NITROSHARE 1
.SH NAME
nitroshare \- launches the NitroShare application
.SH SYNOPSIS
.B nitroshare
[options]
.SH DESCRIPTION
.B NitroShare
is a cross-platform application for sharing files over a local network. Each
device on the network with NitroShare installed can instantly transfer files
and directories to other devices.
